use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/liunina/NLSpecs.git'

platform :ios, '10.0'

target 'NUBlocksKit_Example' do
  pod 'NUBlocksKit', :path => '../'

  target 'NUBlocksKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
